### ISSUE TITLE
Updating to 2024.12 fails due to greater than maximum allowed size

### ISSUE THREAD

**Issue by VACIndustries** [ApolloAutomation/PLT-1#20]
```
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
Linking .pioenvs/apollo-plt-1-b28b9c/firmware.elf
RAM:   [=         ]  14.6% (used 47860 bytes from 327680 bytes)
Flash: [==========]  102.4% (used 1879678 bytes from 1835008 bytes)
Error: The program size (1879678 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================= [FAILED] Took 13.26 seconds =========================
```

**Comment by VACIndustries** [comment]
Looks like the same is happening wiht my H-1:
```
Linking .pioenvs/apollo-h-1-b26464/firmware.elf
RAM:   [=         ]  14.6% (used 47772 bytes from 327680 bytes)
Flash: [==========]  102.5% (used 1880256 bytes from 1835008 bytes)
Error: The program size (1880256 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================= [FAILED] Took 13.14 seconds =========================
```

**Comment by imadunatic** [comment]
Same here

```Linking .pioenvs/apollo-plt-1-a9a978/firmware.elf
RAM:   [=         ]  14.6% (used 47860 bytes from 327680 bytes)
Error: The program size (1880206 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
Flash: [==========]  102.5% (used 1880206 bytes from 1835008 bytes)
========================= [FAILED] Took 18.17 seconds =========================

**Comment by TrevorSchirmer** [comment]
Hello. Thanks for letting us know, the newest ESPHome update is larger so going over the limit. 

The H-1 is fixed. 

You can still add your sensors to Home Assistant through the normal ESPHome integration and not the ESPHome addon. The addon is only needed if you are looking to modify the firmware.

I'm working on the fix for PLT to allow it to import to the ESPHome addon as well as some automated nightly builds so we catch problems earlier on our own. 

So if you don't need to edit our firmware you can get them going by not adding to the ESPHome addon and just using the HA discovered devices side. 

I'll update this ticket when the firmware has been updated though. 

-Trevor

**Comment by TrevorSchirmer** [comment]
@imadunatic @VACIndustries ,

If you would still like to use the ESPHome addon you can reflash your PLTs from our flashing page. They should then import to ESPHome. 

PLT-1 Flashing: https://wiki.apolloautomation.com/products/plt1/plt1-code/
PLT-1B Flashing: https://wiki.apolloautomation.com/products/plt1b/plt1b-code/



Or in ESPHome addon you can edit the yaml and change this

-- For PLT-1
```
packages:
  ApolloAutomation.TEMP_PRO-1: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1_Minimal.yaml
```

For PLT-1B

```
packages:
  ApolloAutomation.TEMP_PRO-1: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1B_Minimal.yaml
```

Apologies for the trouble

**Comment by imadunatic** [comment]
> @imadunatic @VACIndustries ,
> 
> If you would still like to use the ESPHome addon you can reflash your PLTs from our flashing page. They should then import to ESPHome.

Thanks Trevor. I don't really need to use the ESPHome addon. It's probably more trouble than it's worth. Only thing I am changing is a static IP. I have updated to the minimal links you posted, worked fine. Thanks for the quick fix. Plants will be happy to have the sentry back on patrol!

**Comment by VACIndustries** [comment]
@TrevorSchirmer what is the `TEMP_PRO-1` portion of the package definition?

**Comment by TrevorSchirmer** [comment]
> @TrevorSchirmer what is the `TEMP_PRO-1` portion of the package definition?

Corrected, it is just what the project will be named. I didn't notice when copying from another sensor. TEMP_PRO-1 is a POE temperature probe sensor we have for an industrial client. We've not posted it on our site but might in the future.
